/* 
 * Melonloader Mods API
 *
 * API to manipulate and list MelonLoader mods
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MelonLoaderModsAPI.Api;
using MelonLoaderModsAPI.Model;
using MelonLoaderModsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MelonLoaderModsAPI.Test
{
    /// <summary>
    ///  Class for testing Mods
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModsTests
    {
        // TODO uncomment below to declare an instance variable for Mods
        //private Mods instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Mods
            //instance = new Mods();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Mods
        /// </summary>
        [Test]
        public void ModsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Mods
            //Assert.IsInstanceOfType<Mods> (instance, "variable 'instance' is a Mods");
        }



    }

}
