/* 
 * Melonloader Mods API
 *
 * API to manipulate and list MelonLoader mods
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MelonLoaderModsAPI.Api;
using MelonLoaderModsAPI.Model;
using MelonLoaderModsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MelonLoaderModsAPI.Test
{
    /// <summary>
    ///  Class for testing Mod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModTests
    {
        // TODO uncomment below to declare an instance variable for Mod
        //private Mod instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Mod
            //instance = new Mod();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Mod
        /// </summary>
        [Test]
        public void ModInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Mod
            //Assert.IsInstanceOfType<Mod> (instance, "variable 'instance' is a Mod");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Mention'
        /// </summary>
        [Test]
        public void MentionTest()
        {
            // TODO unit test for the property 'Mention'
        }
        /// <summary>
        /// Test the property 'Messageid'
        /// </summary>
        [Test]
        public void MessageidTest()
        {
            // TODO unit test for the property 'Messageid'
        }
        /// <summary>
        /// Test the property 'Versionofmsg'
        /// </summary>
        [Test]
        public void VersionofmsgTest()
        {
            // TODO unit test for the property 'Versionofmsg'
        }
        /// <summary>
        /// Test the property 'Uploaddate'
        /// </summary>
        [Test]
        public void UploaddateTest()
        {
            // TODO unit test for the property 'Uploaddate'
        }
        /// <summary>
        /// Test the property 'Aliases'
        /// </summary>
        [Test]
        public void AliasesTest()
        {
            // TODO unit test for the property 'Aliases'
        }
        /// <summary>
        /// Test the property 'Versions'
        /// </summary>
        [Test]
        public void VersionsTest()
        {
            // TODO unit test for the property 'Versions'
        }

    }

}
