/* 
 * Melonloader Mods API
 *
 * API to manipulate and list MelonLoader mods
 *
 * OpenAPI spec version: 2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MelonLoaderModsAPI.Api;
using MelonLoaderModsAPI.Model;
using MelonLoaderModsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MelonLoaderModsAPI.Test
{
    /// <summary>
    ///  Class for testing ModVersions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModVersionsTests
    {
        // TODO uncomment below to declare an instance variable for ModVersions
        //private ModVersions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModVersions
            //instance = new ModVersions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModVersions
        /// </summary>
        [Test]
        public void ModVersionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModVersions
            //Assert.IsInstanceOfType<ModVersions> (instance, "variable 'instance' is a ModVersions");
        }


        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'ApprovalStatus'
        /// </summary>
        [Test]
        public void ApprovalStatusTest()
        {
            // TODO unit test for the property 'ApprovalStatus'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Modversion'
        /// </summary>
        [Test]
        public void ModversionTest()
        {
            // TODO unit test for the property 'Modversion'
        }
        /// <summary>
        /// Test the property 'Vrchatversion'
        /// </summary>
        [Test]
        public void VrchatversionTest()
        {
            // TODO unit test for the property 'Vrchatversion'
        }
        /// <summary>
        /// Test the property 'Loaderversion'
        /// </summary>
        [Test]
        public void LoaderversionTest()
        {
            // TODO unit test for the property 'Loaderversion'
        }
        /// <summary>
        /// Test the property 'Modtype'
        /// </summary>
        [Test]
        public void ModtypeTest()
        {
            // TODO unit test for the property 'Modtype'
        }
        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Downloadlink'
        /// </summary>
        [Test]
        public void DownloadlinkTest()
        {
            // TODO unit test for the property 'Downloadlink'
        }
        /// <summary>
        /// Test the property 'Sourcelink'
        /// </summary>
        [Test]
        public void SourcelinkTest()
        {
            // TODO unit test for the property 'Sourcelink'
        }
        /// <summary>
        /// Test the property 'Discord'
        /// </summary>
        [Test]
        public void DiscordTest()
        {
            // TODO unit test for the property 'Discord'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Changelog'
        /// </summary>
        [Test]
        public void ChangelogTest()
        {
            // TODO unit test for the property 'Changelog'
        }
        /// <summary>
        /// Test the property 'Updatedate'
        /// </summary>
        [Test]
        public void UpdatedateTest()
        {
            // TODO unit test for the property 'Updatedate'
        }

    }

}
